<?php $this->title = "Cerrar sesión"; ?>
    <div class="bg-white rounded-lg shadow-md p-6 text-center max-w-sm w-full mx-auto mt-16">
      <h3 class="text-xl font-semibold mb-4">Has cerrado sesión</h3>
      <p class="text-sm">
        <a
          href="<?= BASE_URL ?>/login"
          class="text-yellow-600 hover:underline"
          >Iniciar sesión nuevamente</a
        >
      </p>
    </div>

