<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= $this->title ?? 'MiGestor' ?></title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 min-h-screen flex flex-col text-gray-800">

  <?php require __DIR__ . '/header.phtml'; ?>

  <main class="flex-grow">
    <?= $this->content() ?>
  </main>


  <?php require __DIR__ . '/footer.phtml'; ?>

</body>
</html>

